packages:
  - packages/*
  - packages/adapters/*
  - examples/*
  - apps/*
  - docs

onlyBuiltDependencies:
  - bufferutil
  - es5-ext
  - esbuild
  - tiny-secp256k1
  - utf-8-validate

overrides:
  bn.js@>=4.0.0 <4.12.3: '>=4.12.3 <5'
  bn.js@>=5.0.0 <5.2.3: '>=5.2.3 <6'
  defu@>=6.0.0 <=6.1.4: '>=6.1.5 <7'
  esbuild@<=0.24.2: '>=0.25.0'
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  h3@>=1.0.0 <1.15.11: '>=1.15.11 <2'
  js-yaml@<3.14.2: '>=3.14.2'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  lodash@>=4.0.0 <4.18.0: '>=4.18.0 <5'
  mdast-util-to-hast@>=13.0.0 <13.2.1: '>=13.2.1'
  node-forge@>=1.0.0 <1.4.0: '>=1.4.0 <2'
  vite@>=5.2.6 <=5.4.20: '>=5.4.21'
  vite@>=7.1.0 <=7.1.10: '>=7.1.11'
  ws@>=7.0.0 <7.5.11: '>=7.5.11 <8'
  ws@>=8.0.0 <8.21.0: '>=8.21.0 <9'
  gray-matter>js-yaml: ^3.14.1
  vite: 'catalog:'
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.5
  vite-plus: 0.2.5
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: '*'
